# Generated by Django 5.1.7 on 2025-04-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('weather', '0002_alter_location_options_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
