# Generated by Django 5.1.7 on 2025-04-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_location_options_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
    ]
