# Generated by Django 5.1.7 on 2025-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default=None, max_length=190),
            preserve_default=False,
        ),
    ]
